# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
          - 29.2
          - release-snapshot
          - snapshot

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: .elisp

      # Runs a single command using the runners shell
      - name: Check startup
        run: |
          $GITHUB_WORKSPACE/.elisp/scripts/config.sh
          $GITHUB_WORKSPACE/.elisp/scripts/test-startup.sh
